### PR TITLE
++ docker file

### PR DESCRIPTION
**Pull request by jacksonjegathesan**
Change: Added docker file for containerization
Testing: Tested in Dev environment

### CODE REVIEW

**Comment by DanielSanchez97** [comment]
@jacksonjegathesan were you able to get the container to process a vaccine card? When I ran it, there is a missing .so library that python is trying to bind. 

> python verify_card.py --template templates/CDC_card_template_01.png --image /tmp/data/VaccineCard_Daniel.jpg

Traceback (most recent call last):
  File "/app/verify_card.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

I was able to get past this error by adding these apt packages from the top comment:
https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

**Comment by DanielSanchez97** [comment]
@jacksonjegathesan  After that error, I ran into another: 
python verify_card.py --template templates/CDC_card_template_01.png --image /tmp/data/VaccineCard_Daniel.jpg

[INFO] loading images...
[INFO] aligning images...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytesseract/pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/verify_card.py", line 145, in <module>
    title = read_title(aligned, template, fileTag=args["tag"], debug=True)
  File "/app/verify_card.py", line 34, in read_title
    text = pytesseract.image_to_string(rgb)
  File "/usr/local/lib/python3.9/site-packages/pytesseract/pytesseract.py", line 409, in image_to_string
    return {
  File "/usr/local/lib/python3.9/site-packages/pytesseract/pytesseract.py", line 412, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/usr/local/lib/python3.9/site-packages/pytesseract/pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytesseract/pytesseract.py", line 259, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by jacksonjegathesan** [comment]
initially, I was installing requirements.txt with pip

then later while running locally it should be fine

also when I built with docker it seems to be built without any issues

```bash

Sending build context to Docker daemon  13.58MB
Step 1/7 : From python:3
 ---> d92f72c38f7e
Step 2/7 : ENV PYTHONBUFFERED 1
 ---> Using cache
 ---> eaab0f76145f
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> e68edaee62ec
Step 4/7 : ADD . /app
 ---> 9129c1ef91f5
Step 5/7 : COPY requirements.txt /app/requirements.txt
 ---> 0727cacfc6fe
Step 6/7 : RUN pip install -r requirements.txt
 ---> Running in 336b546ef2a3
Collecting imutils==0.5.4
  Downloading imutils-0.5.4.tar.gz (17 kB)
Collecting numpy==1.20.1
  Downloading numpy-1.20.1-cp39-cp39-manylinux2010_x86_64.whl (15.4 MB)
Collecting opencv-python==4.5.1.48
  Downloading opencv_python-4.5.1.48-cp39-cp39-manylinux2014_x86_64.whl (50.4 MB)
Collecting Pillow==8.1.2
  Downloading Pillow-8.1.2-cp39-cp39-manylinux1_x86_64.whl (2.2 MB)
Collecting pytesseract==0.3.7
  Downloading pytesseract-0.3.7.tar.gz (13 kB)
Building wheels for collected packages: imutils, pytesseract
  Building wheel for imutils (setup.py): started
  Building wheel for imutils (setup.py): finished with status 'done'
  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25861 sha256=02fc8403a0c2347cd478899e2fa8bcdcd13e9f7346f1eb7764ae6ef4ca6aa1af
  Stored in directory: /root/.cache/pip/wheels/4b/a5/2d/4a070a801d3a3d93f033d3ee9728f470f514826e89952df3ea
  Building wheel for pytesseract (setup.py): started
  Building wheel for pytesseract (setup.py): finished with status 'done'
  Created wheel for pytesseract: filename=pytesseract-0.3.7-py2.py3-none-any.whl size=13953 sha256=3347b9624cce213aec95cd1de647b3f69052d19d4d8159761b54fec8918d7dbc
  Stored in directory: /root/.cache/pip/wheels/e5/22/c8/c633fb88695e51343e8a57ea85995bd3c4fd02f110c2d4ac91
Successfully built imutils pytesseract
Installing collected packages: Pillow, numpy, pytesseract, opencv-python, imutils
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Successfully installed Pillow-8.1.2 imutils-0.5.4 numpy-1.20.1 opencv-python-4.5.1.48 pytesseract-0.3.7
WARNING: You are using pip version 21.1.3; however, version 21.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Removing intermediate container 336b546ef2a3
 ---> e18cc8fd45d0
Step 7/7 : COPY . /app
 ---> ce3d774b0047
Successfully built ce3d774b0047

```

**Comment by DanielSanchez97** [comment]
Sorry I should have been more precise about where those errors are coming from.  The docker file builds into a docker image correctly like you demonstrated, but when you run the image and try to use the script within it, then you run into those errors. All of those examples are from within a running container when trying to use the tool: 

docker run -it -v /home/daniel/work/vaccination-card-verification/data:/tmp/data --entrypoint /bin/bash vaccine-cards

I ran this command to get a bash shell on the container then ran the previous commands. 

Note that I tagged the image as `vaccine-cards` when building it on my machine. 

docker build . -t vaccine-cards

**Comment by jacksonjegathesan** [comment]
> Sorry I should have been more precise about where those errors are coming from. The docker file builds into a docker image correctly like you demonstrated, but when you run the image and try to use the script within it, then you run into those errors. All of those examples are from within a running container when trying to use the tool:
> 
> docker run -it -v /home/daniel/work/vaccination-card-verification/data:/tmp/data --entrypoint /bin/bash vaccine-cards
> 
> I ran this command to get a bash shell on the container then ran the previous commands.
> 
> Note that I tagged the image as `vaccine cards' when building it on my machine.
> 
> docker build . -t vaccine-cards

seems  that it is due to a python-based container let me rebuild it with an Ubuntu-based container and retest it

**Comment by jacksonjegathesan** [comment]
switched from python to ubuntu container and now I can able to ssh into the container

```bash
sudo docker run -it vaccine_test /bin/bash
```
and run python file with a random image found online

```python
python3 verify_card.py --template templates/CDC_card_template_01.png --image input.jpg
````
logs:

```bash
root@f416d0f4edcb:/home/App# 
root@f416d0f4edcb:/home/App# python3 verify_card.py --template templates/CDC_card_template_01.png --image input.jpg
[INFO] loading images...
[INFO] aligning images...
Valid vaccination card detected!
root@f416d0f4edcb:/home/App# exit
exit
```

**Comment by DanielSanchez97** [comment]
Yep that made it run on my system!

**Pull request merged**
